export const details = [
  { title: 'Grocery', bio: '45% descuento' },
  { title: 'Pharmacy', bio: '$5 descuento' },
  { title: 'Pet', bio: '45% descuento' },
  { title: 'Home', bio: '25% descuento' },
  { title: 'Fashion', bio: '$20 descuento' },
  { title: 'Electronic', bio: '50% descuento' },
  { title: 'Alcohol', bio: '$10 descuento' },
  { title: 'Gas', bio: '$5 descuento' },
  { title: 'Movie', bio: '$5 descuento' },
  { title: 'Entertainment', bio: '$10 descuento' },
  { title: 'Office', bio: '35% descuento' },
  { title: 'Mobile', bio: '20% descuento' },
  { title: 'Sport', bio: '$10 descuento' },
  { title: 'Fast Food', bio: '$5 descuento' },
  { title: 'pizza', bio: '$5 descuento' },
  { title: 'Banking', bio: '$50 descuento' },
  { title: 'Insurance', bio: '$55 descuento' },
  { title: 'Restaurant', bio: '25% descuento' },
  { title: 'Service', bio: '$15% descuento' },
];
